# wit-kv justfile
# Run tasks with: just <target>

# Default target
default: build

# Build all release binaries (wit-kv CLI and wit-kv-server)
build:
    cargo build --workspace --release

# Build only the CLI binary
build-cli:
    cargo build --release -p wit-kv-cli

# Build only the server binary
build-server:
    cargo build --release -p wit-kv-server

# Build the TypeScript client and UI
build-client:
    cd client && npm install && npm run build

# Build everything: binaries, client, and examples
build-all: build build-client build-examples

# Create a distribution with server, client UI, and example config
dist: build-all
    #!/usr/bin/env bash
    set -e
    mkdir -p dist
    cp target/release/wit-kv dist/ 2>/dev/null || true
    cp target/release/wit-kv-server dist/ 2>/dev/null || true
    cp -r client/dist dist/ui
    # Create a sample config with static_path configured
    cat > dist/wit-kv-server.toml << 'EOF'
    # wit-kv Server Configuration
    # Generated by: just dist

    [server]
    bind = "127.0.0.1"
    port = 8080
    # Serve the UI from the ui/ directory
    static_path = "./ui"

    [cors]
    # Enable CORS for local development
    enabled = true
    allow_origins = ["*"]

    [[databases]]
    name = "default"
    path = "./.wit-kv-data"
    EOF
    echo "Distribution created in dist/"
    echo "  - wit-kv (CLI)"
    echo "  - wit-kv-server (HTTP API server)"
    echo "  - ui/ (Web UI)"
    echo "  - wit-kv-server.toml (config with UI enabled)"
    echo ""
    echo "To run: cd dist && ./wit-kv-server"

# Build all example wasm components
build-examples: build-point-filter build-person-filter build-sum-scores build-point-to-magnitude

# Build point-filter component (uses cargo-component)
build-point-filter:
    cd examples/point-filter && cargo component build --release --target wasm32-unknown-unknown

# Build person-filter component (uses cargo-component)
build-person-filter:
    cd examples/person-filter && cargo component build --release --target wasm32-unknown-unknown

# Build sum-scores component (uses cargo-component)
build-sum-scores:
    cd examples/sum-scores && cargo component build --release --target wasm32-unknown-unknown

# Build point-to-magnitude component (uses cargo-component)
build-point-to-magnitude:
    cd examples/point-to-magnitude && cargo component build --release --target wasm32-unknown-unknown

# Run all tests
test:
    cargo test

# Run clippy
clippy:
    cargo clippy

# Run the usage example script
usage-example: build
    ./scripts/usage-example.sh release

# Run the error conditions test script
test-errors: build
    ./scripts/test-errors.sh release

# Run all smoke tests (usage example + map/reduce examples + unit tests)
smoke-test: build build-examples
    #!/usr/bin/env bash
    set -e
    echo "========================================"
    echo "  SMOKE TEST: wit-kv"
    echo "========================================"
    echo ""

    echo ">>> Running unit tests..."
    cargo test
    echo ""

    echo ">>> Running usage example script..."
    ./scripts/usage-example.sh release
    echo ""

    echo ">>> Setting up map/reduce test environment..."
    rm -rf /tmp/smoke-test-kv
    mkdir -p /tmp/smoke-test-kv
    ./target/release/wit-kv init --path /tmp/smoke-test-kv
    ./target/release/wit-kv set-type users --wit test.wit --type-name person --path /tmp/smoke-test-kv
    ./target/release/wit-kv set users alice --value "{age: 30, score: 100}" --path /tmp/smoke-test-kv
    ./target/release/wit-kv set users bob --value "{age: 25, score: 85}" --path /tmp/smoke-test-kv
    ./target/release/wit-kv set users charlie --value "{age: 35, score: 120}" --path /tmp/smoke-test-kv
    echo ""

    echo ">>> Setting up points keyspace for point-filter..."
    ./target/release/wit-kv set-type points \
        --wit examples/point-filter/wit/map.wit \
        --type-name point \
        --path /tmp/smoke-test-kv
    ./target/release/wit-kv set points p1 --value "{x: 10, y: 20}" --path /tmp/smoke-test-kv
    ./target/release/wit-kv set points p2 --value "{x: 50, y: 50}" --path /tmp/smoke-test-kv
    ./target/release/wit-kv set points p3 --value "{x: 150, y: 0}" --path /tmp/smoke-test-kv
    ./target/release/wit-kv set points p4 --value "{x: 3, y: 4}" --path /tmp/smoke-test-kv
    echo ""

    echo ">>> Testing map with point-filter..."
    OUTPUT=$(./target/release/wit-kv map points \
        --module ./examples/point-filter/target/wasm32-unknown-unknown/release/point_filter.wasm \
        --module-wit ./examples/point-filter/wit/map.wit \
        --input-type point \
        --path /tmp/smoke-test-kv 2>&1)
    echo "$OUTPUT"
    # Should filter out p3 (150,0 is outside radius 100) and transform others (double coords)
    if echo "$OUTPUT" | grep -q "3 transformed" && echo "$OUTPUT" | grep -q "1 filtered"; then
        echo "PASSED: point-filter returned 3 transformed, 1 filtered"
    else
        echo "FAILED: point-filter should return 3 transformed, 1 filtered"
        exit 1
    fi
    echo ""

    echo ">>> Testing map with person-filter..."
    # Reuse the users keyspace (already has person type compatible data)
    OUTPUT=$(./target/release/wit-kv map users \
        --module ./examples/person-filter/target/wasm32-unknown-unknown/release/person_filter.wasm \
        --module-wit ./examples/person-filter/wit/map.wit \
        --input-type person \
        --path /tmp/smoke-test-kv 2>&1)
    echo "$OUTPUT"
    # alice (score 100) and charlie (score 120) pass filter, bob (85) filtered out
    if echo "$OUTPUT" | grep -q "2 transformed" && echo "$OUTPUT" | grep -q "1 filtered"; then
        echo "PASSED: person-filter returned 2 transformed, 1 filtered"
    else
        echo "FAILED: person-filter should return 2 transformed, 1 filtered"
        exit 1
    fi
    echo ""

    echo ">>> Testing reduce with sum-scores..."
    OUTPUT=$(./target/release/wit-kv reduce users \
        --module ./examples/sum-scores/target/wasm32-unknown-unknown/release/sum_scores.wasm \
        --module-wit ./examples/sum-scores/wit/reduce.wit \
        --input-type person \
        --state-type total \
        --path /tmp/smoke-test-kv 2>&1)
    echo "$OUTPUT"
    # Should sum all scores: 100 + 85 + 120 = 305, count = 3
    if echo "$OUTPUT" | grep -q "sum: 305" && echo "$OUTPUT" | grep -q "count: 3"; then
        echo "PASSED: sum-scores returned {sum: 305, count: 3}"
    else
        echo "FAILED: sum-scores should return {sum: 305, count: 3}"
        exit 1
    fi
    echo ""

    echo ">>> Testing map with point-to-magnitude (T -> T1 transformation)..."
    OUTPUT=$(./target/release/wit-kv map points \
        --module ./examples/point-to-magnitude/target/wasm32-unknown-unknown/release/point_to_magnitude.wasm \
        --module-wit ./examples/point-to-magnitude/wit/map.wit \
        --input-type point \
        --output-type magnitude \
        --path /tmp/smoke-test-kv 2>&1)
    echo "$OUTPUT"
    # p1(10,20)->500, p2(50,50)->5000, p4(3,4)->25; p3(150,0) filtered (origin check passes, but let's verify output)
    # All 4 points should transform since none are at origin
    if echo "$OUTPUT" | grep -q "distance-squared:" && echo "$OUTPUT" | grep -q "quadrant:"; then
        echo "PASSED: point-to-magnitude produced magnitude records with distance-squared and quadrant"
    else
        echo "FAILED: point-to-magnitude should produce magnitude records"
        exit 1
    fi
    echo ""

    echo "========================================"
    echo "  ALL SMOKE TESTS PASSED"
    echo "========================================"

# Check outdated dependencies for all projects
check-outdated: check-outdated-root check-outdated-point-filter check-outdated-person-filter check-outdated-sum-scores check-outdated-point-to-magnitude

# Check outdated dependencies for root project
check-outdated-root:
    cargo outdated -R

# Check outdated dependencies for point-filter example
check-outdated-point-filter:
    cd examples/point-filter && cargo outdated -R

# Check outdated dependencies for person-filter example
check-outdated-person-filter:
    cd examples/person-filter && cargo outdated -R

# Check outdated dependencies for sum-scores example
check-outdated-sum-scores:
    cd examples/sum-scores && cargo outdated -R

# Check outdated dependencies for point-to-magnitude example
check-outdated-point-to-magnitude:
    cd examples/point-to-magnitude && cargo outdated -R

# Clean build artifacts
clean:
    cargo clean
    rm -rf dist
    rm -rf client/dist
    rm -rf examples/point-filter/target
    rm -rf examples/person-filter/target
    rm -rf examples/sum-scores/target
    rm -rf examples/point-to-magnitude/target

# Run the server with UI (for development)
serve: build-server build-client
    #!/usr/bin/env bash
    set -e
    # Create temp config if not exists
    if [ ! -f wit-kv-server.toml ]; then
        cat > wit-kv-server.toml << 'EOF'
    [server]
    bind = "127.0.0.1"
    port = 8080
    static_path = "./client/dist"

    [cors]
    enabled = true
    allow_origins = ["*"]

    [[databases]]
    name = "default"
    path = "./.wit-kv-data"
    EOF
    fi
    ./target/release/wit-kv-server --config wit-kv-server.toml
