# wit-kv justfile
# Run tasks with: just <target>

# Default target
default: build

# Build all release binaries (wit-kv CLI and wit-kv-server)
build:
    cargo build --workspace --release

# Build only the CLI binary
build-cli:
    cargo build --release -p wit-kv-cli

# Build only the wit-file binary
build-wit-file:
    cargo build --release -p wit-file

# Build only the wit-fs binary
build-wit-fs:
    cargo build --release -p wit-fs

# Build only the server binary
build-server:
    cargo build --release -p wit-kv-server

# Build the TypeScript client and UI
build-client:
    cd client && npm install && npm run build

# Verify required external tools are installed
check-tools:
    #!/usr/bin/env bash
    set -e
    missing=()
    command -v wasm-tools >/dev/null || missing+=("wasm-tools (cargo install wasm-tools)")
    command -v cargo-component >/dev/null || missing+=("cargo-component (cargo install cargo-component)")
    rustup target list --installed | grep -q wasm32-unknown-unknown || missing+=("wasm32-unknown-unknown target (rustup target add wasm32-unknown-unknown)")
    command -v npm >/dev/null || missing+=("npm/node (install Node.js >= 20)")
    if [ ${#missing[@]} -gt 0 ]; then
        echo "Missing required tools:"
        for tool in "${missing[@]}"; do
            echo "  - $tool"
        done
        exit 1
    fi

# Build everything: binaries, client, examples, and playground
build-all: check-tools build build-client build-examples build-playground

# Create a self-contained distribution of the entire project
dist: build-all
    #!/usr/bin/env bash
    set -e
    rm -rf dist
    mkdir -p dist

    # Binaries
    cp target/release/wit-kv dist/
    cp target/release/wit-kv-server dist/
    cp target/release/wit-file dist/
    cp target/release/wit-fs dist/

    # Web UIs
    cp -r client/dist dist/ui
    cp -r playground/dist dist/playground

    # Examples (wasm + wit + src)
    for example in point-filter person-filter sum-scores point-to-magnitude; do
        mkdir -p dist/examples/$example/{wit,src}
        cp examples/$example/wit/*.wit dist/examples/$example/wit/
        cp examples/$example/src/*.rs dist/examples/$example/src/
        # Copy the built wasm component (underscored name)
        wasm_name=$(echo "$example" | tr '-' '_')
        cp examples/$example/target/wasm32-unknown-unknown/release/${wasm_name}.wasm \
            dist/examples/$example/
    done

    # Docs
    mkdir -p dist/docs/wit-fs
    cp README.md dist/docs/README.md
    cp crates/wit-kv/README.md dist/docs/wit-kv.md
    cp crates/wit-file/README.md dist/docs/wit-file.md
    cp crates/wit-fs/README.md dist/docs/wit-fs.md
    cp crates/wit-fs/docs/*.md dist/docs/wit-fs/

    # Config
    cat > dist/wit-kv-server.toml << 'EOF'
    # wit-kv Server Configuration
    # Generated by: just dist

    [server]
    bind = "127.0.0.1"
    port = 8080
    # Serve the playground from the playground/ directory
    # Change to "./ui" for the basic explorer UI
    static_path = "./playground"

    [[databases]]
    name = "default"
    path = "./.wit-kv-data"
    EOF

    # WIT schema
    cp crates/wit-kv/kv.wit dist/

    echo ""
    echo "Distribution created in dist/"
    echo ""
    echo "  Binaries:"
    echo "    wit-kv           CLI client"
    echo "    wit-kv-server    HTTP API server"
    echo "    wit-file         WIT-typed file tool"
    echo "    wit-fs           FUSE filesystem"
    echo ""
    echo "  Web UIs:"
    echo "    ui/              Basic explorer UI"
    echo "    playground/      Advanced playground with binary viewer"
    echo ""
    echo "  Examples:"
    echo "    examples/point-filter/"
    echo "    examples/person-filter/"
    echo "    examples/sum-scores/"
    echo "    examples/point-to-magnitude/"
    echo ""
    echo "  Docs:"
    echo "    docs/README.md, wit-kv.md, wit-file.md, wit-fs.md"
    echo "    docs/wit-fs/     (design + quick-start guide)"
    echo ""
    echo "  Config & Schema:"
    echo "    wit-kv-server.toml"
    echo "    kv.wit"
    echo ""
    echo "To run: cd dist && ./wit-kv-server"

# Build wit-ast wasm component
build-wit-ast:
    cd crates/wit-ast && cargo build --release --target wasm32-unknown-unknown

# Build wit-ast JS/WASM bindings (requires wasm-tools)
build-wit-ast-js: build-wit-ast
    cd crates/wit-ast/bindings/js && npm install && npm run build

# Build the playground (requires wit-ast JS bindings and example components)
build-playground: build-wit-ast-js build-client build-examples
    #!/usr/bin/env bash
    set -e
    # Copy wit-ast bindings to src/lib for proper ES module handling
    mkdir -p playground/src/lib/witast
    cp -r crates/wit-ast/bindings/js/dist/* playground/src/lib/witast/
    # Patch witast.js to remove Node.js code (browser-only)
    sed 's/const isNode = typeof process.*//; s/let _fs;//; s/if (isNode) {/if (false) {/; s/_fs = _fs.*//; s/return WebAssembly.compile(await _fs.readFile(url));//' playground/src/lib/witast/witast.js > playground/src/lib/witast/witast.js.tmp && mv playground/src/lib/witast/witast.js.tmp playground/src/lib/witast/witast.js
    # Copy example WASM components to public/wasm
    mkdir -p playground/public/wasm
    cp examples/point-filter/target/wasm32-unknown-unknown/release/point_filter.wasm playground/public/wasm/
    cp examples/person-filter/target/wasm32-unknown-unknown/release/person_filter.wasm playground/public/wasm/
    cp examples/sum-scores/target/wasm32-unknown-unknown/release/sum_scores.wasm playground/public/wasm/
    cp examples/point-to-magnitude/target/wasm32-unknown-unknown/release/point_to_magnitude.wasm playground/public/wasm/
    # Build playground
    cd playground && npm install && npm run build

# Run playground with the server (production mode)
playground clean="true": build-server build-playground
    #!/usr/bin/env bash
    set -e
    if [ "{{clean}}" = "true" ]; then
        echo "Cleaning playground data..."
        rm -rf .wit-kv-playground
    fi
    echo "Starting wit-kv-server with playground UI..."
    echo "Open http://localhost:8080 in your browser"
    ./target/release/wit-kv-server --config playground/resources/server.toml

# Run playground in development mode (with Vite HMR)
playground-dev clean="true": build-server build-wit-ast-js build-examples
    #!/usr/bin/env bash
    set -e
    # Copy wit-ast bindings to src/lib for proper ES module handling
    mkdir -p playground/src/lib/witast
    cp -r crates/wit-ast/bindings/js/dist/* playground/src/lib/witast/
    # Patch witast.js to remove Node.js code (browser-only)
    sed 's/const isNode = typeof process.*//; s/let _fs;//; s/if (isNode) {/if (false) {/; s/_fs = _fs.*//; s/return WebAssembly.compile(await _fs.readFile(url));//' playground/src/lib/witast/witast.js > playground/src/lib/witast/witast.js.tmp && mv playground/src/lib/witast/witast.js.tmp playground/src/lib/witast/witast.js
    # Copy example WASM components to public/wasm
    mkdir -p playground/public/wasm
    cp examples/point-filter/target/wasm32-unknown-unknown/release/point_filter.wasm playground/public/wasm/
    cp examples/person-filter/target/wasm32-unknown-unknown/release/person_filter.wasm playground/public/wasm/
    cp examples/sum-scores/target/wasm32-unknown-unknown/release/sum_scores.wasm playground/public/wasm/
    cp examples/point-to-magnitude/target/wasm32-unknown-unknown/release/point_to_magnitude.wasm playground/public/wasm/
    # Install deps (use subshell to preserve cwd)
    (cd playground && npm install)
    # Clean playground data if requested
    if [ "{{clean}}" = "true" ]; then
        echo "Cleaning playground data..."
        rm -rf .wit-kv-playground
    fi
    # Start server in background
    echo "Starting wit-kv-server on port 8080..."
    ./target/release/wit-kv-server --config playground/resources/server-dev.toml &
    SERVER_PID=$!
    trap "kill $SERVER_PID 2>/dev/null" EXIT
    echo "Starting Vite dev server..."
    cd playground && npm run dev

# Build all example wasm components
build-examples: build-point-filter build-person-filter build-sum-scores build-point-to-magnitude

# Build point-filter component (uses cargo-component)
build-point-filter:
    cd examples/point-filter && cargo component build --release --target wasm32-unknown-unknown

# Build person-filter component (uses cargo-component)
build-person-filter:
    cd examples/person-filter && cargo component build --release --target wasm32-unknown-unknown

# Build sum-scores component (uses cargo-component)
build-sum-scores:
    cd examples/sum-scores && cargo component build --release --target wasm32-unknown-unknown

# Build point-to-magnitude component (uses cargo-component)
build-point-to-magnitude:
    cd examples/point-to-magnitude && cargo component build --release --target wasm32-unknown-unknown

# Run all tests
test: test-errors smoke-test-wit-file smoke-test-wit-fs smoke-test

# Lint all projects (Rust clippy + TypeScript type-checking)
lint:
    #!/usr/bin/env bash
    set -e
    echo ">>> Clippy: workspace..."
    cargo clippy --workspace -- -D warnings
    echo ""
    echo ">>> Clippy: wit-ast..."
    (cd crates/wit-ast && cargo clippy -- -D warnings)
    echo ""
    echo ">>> TypeScript: client..."
    (cd client && npm install --silent && npx tsc)
    echo ""
    echo ">>> TypeScript: playground..."
    if [ -d playground/src/lib/witast ]; then
        (cd playground && npm install --silent && npx tsc --noEmit)
    else
        echo "  Skipped (witast bindings not built). Run 'just build-wit-ast-js' first."
    fi
    echo ""
    echo "All lint checks passed."

# Run the usage example script
usage-example: build
    ./crates/wit-kv-cli/scripts/usage-example.sh release

# Run the error conditions test script
test-errors: build
    ./crates/wit-kv-cli/scripts/test-errors.sh release

# Run wit-file smoke tests (roundtrip all WIT types)
smoke-test-wit-file: build
    ./crates/wit-file/scripts/smoke-test.sh release

# Run wit-fs smoke tests (mount, write, read, validate, error handling)
smoke-test-wit-fs: build
    ./crates/wit-fs/scripts/smoke-test.sh release

# Run all smoke tests (usage example + map/reduce examples + unit tests)
smoke-test: build build-examples
    #!/usr/bin/env bash
    set -e
    echo "========================================"
    echo "  SMOKE TEST: wit-kv"
    echo "========================================"
    echo ""

    echo ">>> Running unit tests..."
    cargo test
    echo ""

    echo ">>> Running usage example script..."
    ./crates/wit-kv-cli/scripts/usage-example.sh release
    echo ""

    echo ">>> Setting up map/reduce test environment..."
    rm -rf /tmp/smoke-test-kv
    mkdir -p /tmp/smoke-test-kv
    ./target/release/wit-kv init --path /tmp/smoke-test-kv
    ./target/release/wit-kv set-type users --wit examples/sum-scores/wit/reduce.wit --type-name person --path /tmp/smoke-test-kv
    ./target/release/wit-kv set users alice --value "{age: 30, score: 100}" --path /tmp/smoke-test-kv
    ./target/release/wit-kv set users bob --value "{age: 25, score: 85}" --path /tmp/smoke-test-kv
    ./target/release/wit-kv set users charlie --value "{age: 35, score: 120}" --path /tmp/smoke-test-kv
    echo ""

    echo ">>> Setting up points keyspace for point-filter..."
    ./target/release/wit-kv set-type points \
        --wit examples/point-filter/wit/map.wit \
        --type-name point \
        --path /tmp/smoke-test-kv
    ./target/release/wit-kv set points p1 --value "{x: 10, y: 20}" --path /tmp/smoke-test-kv
    ./target/release/wit-kv set points p2 --value "{x: 50, y: 50}" --path /tmp/smoke-test-kv
    ./target/release/wit-kv set points p3 --value "{x: 150, y: 0}" --path /tmp/smoke-test-kv
    ./target/release/wit-kv set points p4 --value "{x: 3, y: 4}" --path /tmp/smoke-test-kv
    echo ""

    echo ">>> Testing map with point-filter..."
    OUTPUT=$(./target/release/wit-kv map points \
        --module ./examples/point-filter/target/wasm32-unknown-unknown/release/point_filter.wasm \
        --module-wit ./examples/point-filter/wit/map.wit \
        --input-type point \
        --path /tmp/smoke-test-kv 2>&1)
    echo "$OUTPUT"
    # Should filter out p3 (150,0 is outside radius 100) and transform others (double coords)
    if echo "$OUTPUT" | grep -q "3 transformed" && echo "$OUTPUT" | grep -q "1 filtered"; then
        echo "PASSED: point-filter returned 3 transformed, 1 filtered"
    else
        echo "FAILED: point-filter should return 3 transformed, 1 filtered"
        exit 1
    fi
    echo ""

    echo ">>> Testing map with person-filter..."
    # Reuse the users keyspace (already has person type compatible data)
    OUTPUT=$(./target/release/wit-kv map users \
        --module ./examples/person-filter/target/wasm32-unknown-unknown/release/person_filter.wasm \
        --module-wit ./examples/person-filter/wit/map.wit \
        --input-type person \
        --path /tmp/smoke-test-kv 2>&1)
    echo "$OUTPUT"
    # alice (score 100) and charlie (score 120) pass filter, bob (85) filtered out
    if echo "$OUTPUT" | grep -q "2 transformed" && echo "$OUTPUT" | grep -q "1 filtered"; then
        echo "PASSED: person-filter returned 2 transformed, 1 filtered"
    else
        echo "FAILED: person-filter should return 2 transformed, 1 filtered"
        exit 1
    fi
    echo ""

    echo ">>> Testing reduce with sum-scores..."
    OUTPUT=$(./target/release/wit-kv reduce users \
        --module ./examples/sum-scores/target/wasm32-unknown-unknown/release/sum_scores.wasm \
        --module-wit ./examples/sum-scores/wit/reduce.wit \
        --input-type person \
        --state-type total \
        --path /tmp/smoke-test-kv 2>&1)
    echo "$OUTPUT"
    # Should sum all scores: 100 + 85 + 120 = 305, count = 3
    if echo "$OUTPUT" | grep -q "sum: 305" && echo "$OUTPUT" | grep -q "count: 3"; then
        echo "PASSED: sum-scores returned {sum: 305, count: 3}"
    else
        echo "FAILED: sum-scores should return {sum: 305, count: 3}"
        exit 1
    fi
    echo ""

    echo ">>> Testing map with point-to-magnitude (T -> T1 transformation)..."
    OUTPUT=$(./target/release/wit-kv map points \
        --module ./examples/point-to-magnitude/target/wasm32-unknown-unknown/release/point_to_magnitude.wasm \
        --module-wit ./examples/point-to-magnitude/wit/map.wit \
        --input-type point \
        --output-type magnitude \
        --path /tmp/smoke-test-kv 2>&1)
    echo "$OUTPUT"
    # p1(10,20)->500, p2(50,50)->5000, p4(3,4)->25; p3(150,0) filtered (origin check passes, but let's verify output)
    # All 4 points should transform since none are at origin
    if echo "$OUTPUT" | grep -q "distance-squared:" && echo "$OUTPUT" | grep -q "quadrant:"; then
        echo "PASSED: point-to-magnitude produced magnitude records with distance-squared and quadrant"
    else
        echo "FAILED: point-to-magnitude should produce magnitude records"
        exit 1
    fi
    echo ""

    echo "========================================"
    echo "  ALL SMOKE TESTS PASSED"
    echo "========================================"

# Check outdated dependencies for all projects
check-outdated: check-outdated-root check-outdated-wit-ast check-outdated-point-filter check-outdated-person-filter check-outdated-sum-scores check-outdated-point-to-magnitude

# Check outdated dependencies for root project
check-outdated-root:
    cargo outdated -R

# Check outdated dependencies for wit-ast
check-outdated-wit-ast:
    cd crates/wit-ast && cargo outdated -R

# Check outdated dependencies for point-filter example
check-outdated-point-filter:
    cd examples/point-filter && cargo outdated -R

# Check outdated dependencies for person-filter example
check-outdated-person-filter:
    cd examples/person-filter && cargo outdated -R

# Check outdated dependencies for sum-scores example
check-outdated-sum-scores:
    cd examples/sum-scores && cargo outdated -R

# Check outdated dependencies for point-to-magnitude example
check-outdated-point-to-magnitude:
    cd examples/point-to-magnitude && cargo outdated -R

# Clean build artifacts
clean:
    cargo clean
    rm -rf dist
    rm -rf client/dist
    rm -rf playground/dist
    rm -rf playground/src/lib/witast
    rm -rf playground/node_modules
    rm -rf crates/wit-ast/target
    rm -rf examples/point-filter/target
    rm -rf examples/person-filter/target
    rm -rf examples/sum-scores/target
    rm -rf examples/point-to-magnitude/target

# Deep clean: remove ALL build artifacts (as close to fresh checkout as possible)
clean-all: clean
    rm -rf client/node_modules
    rm -rf crates/wit-ast/bindings/js/node_modules
    rm -rf crates/wit-ast/bindings/js/dist

# Run the server with UI (for development)
serve: build-server build-client
    #!/usr/bin/env bash
    set -e
    # Create temp config if not exists
    if [ ! -f wit-kv-server.toml ]; then
        cat > wit-kv-server.toml << 'EOF'
    [server]
    bind = "127.0.0.1"
    port = 8080
    static_path = "./client/dist"

    [cors]
    enabled = true
    allow_origins = ["*"]

    [[databases]]
    name = "default"
    path = "./.wit-kv-data"
    EOF
    fi
    ./target/release/wit-kv-server --config wit-kv-server.toml
