// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
pub type Point = wit_kv::typed_map::types::Point;
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_filter_cabi<T: Guest>(arg0: i32, arg1: i32) -> i32 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::filter(wit_kv::typed_map::types::Point {
        x: arg0,
        y: arg1,
    });
    match result0 {
        true => 1,
        false => 0,
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_transform_cabi<T: Guest>(arg0: i32, arg1: i32) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::transform(wit_kv::typed_map::types::Point {
        x: arg0,
        y: arg1,
    });
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    let wit_kv::typed_map::types::Point { x: x2, y: y2 } = result0;
    *ptr1.add(0).cast::<i32>() = _rt::as_i32(x2);
    *ptr1.add(4).cast::<i32>() = _rt::as_i32(y2);
    ptr1
}
pub trait Guest {
    /// Filter determines if a point should be processed.
    /// Returns true if the point should be passed to transform.
    fn filter(value: Point) -> bool;
    /// Transform a point to a new point.
    /// Only called for points where filter returned true.
    fn transform(value: Point) -> Point;
}
#[doc(hidden)]
macro_rules! __export_world_typed_map_module_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "filter")] unsafe extern "C" fn
        export_filter(arg0 : i32, arg1 : i32,) -> i32 { unsafe { $($path_to_types)*::
        _export_filter_cabi::<$ty > (arg0, arg1) } } #[unsafe (export_name =
        "transform")] unsafe extern "C" fn export_transform(arg0 : i32, arg1 : i32,) -> *
        mut u8 { unsafe { $($path_to_types)*:: _export_transform_cabi::<$ty > (arg0,
        arg1) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_typed_map_module_cabi;
#[repr(align(4))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 8]);
static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 8]);
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod wit_kv {
    pub mod typed_map {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            /// A 2D point with integer coordinates
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct Point {
                pub x: i32,
                pub y: i32,
            }
            impl ::core::fmt::Debug for Point {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Point")
                        .field("x", &self.x)
                        .field("y", &self.y)
                        .finish()
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_typed_map_module_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_typed_map_module_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_typed_map_module_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:wit-kv:typed-map@0.1.0:typed-map-module:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 311] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xb0\x01\x01A\x02\x01\
A\x08\x01B\x02\x01r\x02\x01xz\x01yz\x04\0\x05point\x03\0\0\x03\0\x1cwit-kv:typed\
-map/types@0.1.0\x05\0\x02\x03\0\0\x05point\x03\0\x05point\x03\0\x01\x01@\x01\x05\
value\x02\0\x7f\x04\0\x06filter\x01\x03\x01@\x01\x05value\x02\0\x02\x04\0\x09tra\
nsform\x01\x04\x04\0'wit-kv:typed-map/typed-map-module@0.1.0\x04\0\x0b\x16\x01\0\
\x10typed-map-module\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-comp\
onent\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
