// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
pub type Point = wit_kv::point_to_magnitude::types::Point;
pub type Magnitude = wit_kv::point_to_magnitude::types::Magnitude;
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_filter_cabi<T: Guest>(arg0: i32, arg1: i32) -> i32 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::filter(wit_kv::point_to_magnitude::types::Point {
        x: arg0,
        y: arg1,
    });
    match result0 {
        true => 1,
        false => 0,
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_transform_cabi<T: Guest>(arg0: i32, arg1: i32) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::transform(wit_kv::point_to_magnitude::types::Point {
        x: arg0,
        y: arg1,
    });
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    let wit_kv::point_to_magnitude::types::Magnitude {
        distance_squared: distance_squared2,
        quadrant: quadrant2,
    } = result0;
    *ptr1.add(0).cast::<i64>() = _rt::as_i64(distance_squared2);
    *ptr1.add(8).cast::<u8>() = (_rt::as_i32(quadrant2)) as u8;
    ptr1
}
pub trait Guest {
    /// Filter determines if a point should be processed.
    /// Returns true if the point should be passed to transform.
    fn filter(value: Point) -> bool;
    /// Transform a point into magnitude information.
    /// Only called for points where filter returned true.
    fn transform(value: Point) -> Magnitude;
}
#[doc(hidden)]
macro_rules! __export_world_typed_map_module_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "filter")] unsafe extern "C" fn
        export_filter(arg0 : i32, arg1 : i32,) -> i32 { unsafe { $($path_to_types)*::
        _export_filter_cabi::<$ty > (arg0, arg1) } } #[unsafe (export_name =
        "transform")] unsafe extern "C" fn export_transform(arg0 : i32, arg1 : i32,) -> *
        mut u8 { unsafe { $($path_to_types)*:: _export_transform_cabi::<$ty > (arg0,
        arg1) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_typed_map_module_cabi;
#[repr(align(8))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 16]);
static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 16]);
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod wit_kv {
    pub mod point_to_magnitude {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            /// A 2D point with integer coordinates (input type)
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct Point {
                pub x: i32,
                pub y: i32,
            }
            impl ::core::fmt::Debug for Point {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Point")
                        .field("x", &self.x)
                        .field("y", &self.y)
                        .finish()
                }
            }
            /// Magnitude information derived from a point (output type)
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct Magnitude {
                /// Distance squared from origin (x² + y²)
                pub distance_squared: u64,
                /// Quadrant number (1-4)
                pub quadrant: u8,
            }
            impl ::core::fmt::Debug for Magnitude {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Magnitude")
                        .field("distance-squared", &self.distance_squared)
                        .field("quadrant", &self.quadrant)
                        .finish()
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_typed_map_module_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_typed_map_module_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_typed_map_module_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:wit-kv:point-to-magnitude@0.1.0:typed-map-module:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 404] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x8d\x02\x01A\x02\x01\
A\x0a\x01B\x04\x01r\x02\x01xz\x01yz\x04\0\x05point\x03\0\0\x01r\x02\x10distance-\
squaredw\x08quadrant}\x04\0\x09magnitude\x03\0\x02\x03\0%wit-kv:point-to-magnitu\
de/types@0.1.0\x05\0\x02\x03\0\0\x05point\x03\0\x05point\x03\0\x01\x02\x03\0\0\x09\
magnitude\x03\0\x09magnitude\x03\0\x03\x01@\x01\x05value\x02\0\x7f\x04\0\x06filt\
er\x01\x05\x01@\x01\x05value\x02\0\x04\x04\0\x09transform\x01\x06\x04\00wit-kv:p\
oint-to-magnitude/typed-map-module@0.1.0\x04\0\x0b\x16\x01\0\x10typed-map-module\
\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10\
wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
